from dotenv import load_dotenv
load_dotenv()

from fastapi import FastAPI, HTTPException, UploadFile, File
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from crewai import Crew
from agents import reader, question, evaluation, feedback
from tasks import create_task1, create_task2, create_task3, create_task4
from pdf_handler import extract_text_from_pdf
import os


app = FastAPI(title="Quiz AI API")

# Allow CORS for the React frontend
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # Adjust in production
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Store state between calls. In production, use a proper database or cache.
# We map a unique session ID to the task2 object so we can pass it to task3.
sessions = {}

class GenerateRequest(BaseModel):
    session_id: str
    topic: str
    is_text: bool = False
    input_type: str = "topic"  # "topic", "text", "pdf"
    num_questions: int = 3
    difficulty: str = "Medium"

class EvaluateRequest(BaseModel):
    session_id: str
    user_answers: list[str]

@app.post("/upload_pdf")
async def upload_pdf(file: UploadFile = File(...)):
    if not file.filename.lower().endswith(".pdf"):
        raise HTTPException(status_code=400, detail="Only PDF files are supported.")
    
    try:
        temp_dir = "temp_uploads"
        os.makedirs(temp_dir, exist_ok=True)
        file_path = os.path.join(temp_dir, file.filename)
        
        with open(file_path, "wb") as f:
            content = await file.read()
            f.write(content)
            
        extracted_text = extract_text_from_pdf(file_path)
        
        # Clean up temp file after reading
        if os.path.exists(file_path):
            os.remove(file_path)
            
        return {
            "filename": file.filename,
            "text": extracted_text
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to process PDF: {str(e)}")

@app.post("/generate_quiz")
async def generate_quiz(req: GenerateRequest):
    try:
        content = req.topic
        inp_type = req.input_type
        if req.is_text and inp_type == "topic":
            inp_type = "text"

        # Escape curly braces in content to prevent CrewAI template errors on text with braces like {url1}
        safe_content = content.replace("{", "{{").replace("}", "}}")

        if inp_type == "pdf":
            task1_description = (
                f"Analyze the following PDF content carefully. Extract key concepts, definitions, and processes. "
                f"CRITICAL REQUIREMENT: For any concept or technical term in the PDF (such as 'Few shot prompting', 'Chain of thought', etc.) "
                f"that has only a brief or shallow explanation, YOU MUST USE search_tool to search the web and gather rich additional context:\n\n{safe_content}"
            )
        elif inp_type == "text":
            task1_description = f"Read and summarize the following content:\n{safe_content}"
        else:
            task1_description = f"Search and summarize key concepts about: {safe_content}"

        task1 = create_task1(task1_description, input_type=inp_type)
        task2 = create_task2(task1, num_questions=req.num_questions, difficulty=req.difficulty)

        crew1 = Crew(
            agents=[reader, question],
            tasks=[task1, task2],
            verbose=True
        )
        
        # Run Crew 1
        crew1.kickoff(inputs={"content": safe_content})
        
        # Save task2 in session memory for later evaluation
        sessions[req.session_id] = task2
        
        # Instead of returning raw crew output, we will return the text 
        # generated by task2, which contains the questions and options.
        return {"questions_text": str(task2.output)}
        
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@app.post("/evaluate_quiz")
async def evaluate_quiz(req: EvaluateRequest):
    try:
        if req.session_id not in sessions:
            raise HTTPException(status_code=404, detail="Session not found. Did you generate a quiz first?")
            
        task2 = sessions[req.session_id]
        
        # Format the user answers for task3
        answers_str = "\\n".join([f"Q{i+1}: {ans}" for i, ans in enumerate(req.user_answers)])
        
        task3 = create_task3(answers_str, task2)
        task4 = create_task4(task3)
        
        crew2 = Crew(
            agents=[evaluation, feedback],
            tasks=[task3, task4],
            verbose=True
        )
        
        # Run Crew 2
        result = crew2.kickoff()
        
        # Extract per-task outputs separately
        evaluation_text = str(task3.output) if task3.output else ""
        feedback_text = str(task4.output) if task4.output else ""

        # Save results to disk
        os.makedirs("memory", exist_ok=True)
        with open("memory/results.txt", "a") as f:
            f.write(f"\n{'='*60}\n")
            f.write(f"Session: {req.session_id}\n")
            f.write(f"User Answers:\n{answers_str}\n")
            f.write(f"Evaluation:\n{evaluation_text}\n")
            f.write(f"Feedback:\n{feedback_text}\n")
            
        return {
            "evaluation": evaluation_text,
            "feedback": feedback_text
        }
        
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

# Run with: uvicorn api:app --reload
if __name__ == "__main__":
    import uvicorn
    uvicorn.run("api:app", host="127.0.0.1", port=8000, reload=True)

